services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    hostname: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file: 
      - stack.env

  web:
    build: 
      context: .
      dockerfile: Dockerfile.web
    command: >
      sh -c "
        cd ./backend &&
        python manage.py makemigrations &&
        python manage.py collectstatic --noinput &&
        python manage.py migrate &&
        daphne -e ssl:8040:privateKey=$$SSL_DIR/priv.pem:certKey=$$SSL_DIR/pub.pem backend.asgi:application"
    volumes:
      - .:/code
    ports:
      - "8040:8040"
    depends_on:
      - db
    env_file: 
      - stack.env

volumes:
  pgdata: