services:
  valkey:
    image: bitnami/valkey:latest
    hostname: valkey
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - vkdata:/data
  db:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.db
    hostname: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file: 
      - stack.env

  web: 
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile.web
    command: >
      sh -c "
        cd ./backend &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        daphne -e ssl:8040:privateKey=$$SSL_DIR/priv.pem:certKey=$$SSL_DIR/pub.pem backend.asgi:application"
    volumes:
      - .:/code
    ports:
      - "8040:8040"
    expose:
      - "8040"
    depends_on:
      - db
    env_file: 
      - stack.env
    
  celery:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.celery
    command: >
      sh -c "
        cd ./backend &&
        celery -A backend worker --pool=solo -l INFO"
    volumes:
      - .:/code
    depends_on:
      - db
      - valkey
    env_file: 
      - stack.env

  flower:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.celery
    command: >
      sh -c "
        cd ./backend &&
        celery -A backend --broker="$$CELERY_BROKER_URL" flower"
    volumes:
      - .:/code
    ports:
      - "5555:5555"
    expose:
      - "5555"
    depends_on:
      - db
      - valkey
    env_file: 
      - stack.env

volumes:
  pgdata:
  vkdata: