services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: 
      context: .
      dockerfile: Dockerfile.daphne
    command: >
      sh -c "
        cd ./backend &&
        daphne -e ssl:8040:privateKey=/usr/local/share/ca-certificates/priv.pem:certKey=/usr/local/share/ca-certificates/pub.pem backend.asgi:application"
    volumes:
      - .:/code
    ports:
      - "8040:8040"
    depends_on:
      - db
    env_file:
      - stack.env
#     secrets:
#       - smb_credentials
# secrets:
#   smb_credentials:
#     file: ./credentials.json