# Generated by Django 4.2.14 on 2024-08-08 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fwpods_be", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                ("album_id", models.AutoField(primary_key=True, serialize=False)),
                ("album_name", models.CharField(max_length=100)),
                ("artist", models.CharField(max_length=100)),
                ("release_date", models.DateField()),
                ("release_year", models.IntegerField()),
                ("genre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                ("playlist_id", models.AutoField(primary_key=True, serialize=False)),
                ("playlist_name", models.CharField(max_length=100)),
                ("songs", models.JSONField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "song_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("favorites", models.IntegerField()),
                ("song_name", models.CharField(max_length=100)),
                ("duration", models.DurationField()),
                (
                    "album_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fwpods_be.album",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="playlists_listens_window",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("songs", models.JSONField()),
                (
                    "playlist_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fwpods_be.playlist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="path_to_item",
            fields=[
                ("path_id", models.AutoField(primary_key=True, serialize=False)),
                ("path", models.CharField(max_length=100)),
                (
                    "album_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fwpods_be.album",
                    ),
                ),
                (
                    "song_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fwpods_be.song"
                    ),
                ),
            ],
        ),
    ]
