# Generated by Django 4.2.14 on 2024-08-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fwpods_be", "0002_album_playlist_song_playlists_listens_window_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="release_date",
            field=models.DateField(null=True),
        ),
    ]
