# Generated by Django 4.2.14 on 2024-08-08 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fwpods_be", "0003_alter_album_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="path_to_item",
            name="album_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fwpods_be.album",
            ),
        ),
        migrations.AlterField(
            model_name="path_to_item",
            name="song_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fwpods_be.song",
            ),
        ),
    ]
