# Generated by Django 4.2.14 on 2024-08-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fwpods_be", "0005_alter_song_song_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="release_year",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="songs",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="favorites",
            field=models.IntegerField(null=True),
        ),
    ]
