# Generated by Django 4.2.14 on 2024-08-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fwpods_be", "0006_alter_album_release_year_alter_playlist_songs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="duration",
            field=models.DurationField(null=True),
        ),
    ]
