# Generated by Django 4.2.14 on 2024-08-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fwpods_be", "0007_alter_song_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="path_to_item",
            name="path",
            field=models.CharField(max_length=1000),
        ),
    ]
