# Generated by Django 4.2.14 on 2024-08-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fwpods_be", "0009_alter_album_album_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="album_id",
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="album",
            name="genre",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="song_id",
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
