# Generated by Django 4.2.14 on 2024-08-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fwpods_be", "0010_alter_album_album_id_alter_album_genre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="album_name",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="song",
            name="song_name",
            field=models.CharField(max_length=1000),
        ),
    ]
