# Generated by Django 4.2.14 on 2024-08-09 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fwpods_be", "0011_alter_album_album_name_alter_song_song_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("artist_id", models.AutoField(primary_key=True, serialize=False)),
                ("artist_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="album",
            name="artist",
            field=models.CharField(max_length=1000),
        ),
        migrations.AddField(
            model_name="song",
            name="artist_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fwpods_be.artist",
            ),
        ),
    ]
