# Generated by Django 4.2.14 on 2024-08-10 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fwpods_be", "0012_artist_alter_album_artist_song_artist_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="songs",
        ),
        migrations.CreateModel(
            name="TransactionWindow",
            fields=[
                ("listen_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "playlist_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fwpods_be.playlist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaylistSongs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "playlist_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fwpods_be.playlist",
                    ),
                ),
                (
                    "song_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fwpods_be.song"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LikedSongs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "song_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fwpods_be.song"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
