# Generated by Django 4.2.14 on 2024-08-15 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fwpods_be", "0013_remove_playlist_songs_transactionwindow_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrequentlyWeightedPlaylist",
            fields=[
                ("fwp_id", models.AutoField(primary_key=True, serialize=False)),
                ("wn_node", models.CharField(max_length=1000000)),
                ("weight", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Runtimes",
            fields=[
                ("runtime_id", models.AutoField(primary_key=True, serialize=False)),
                ("runtime_name", models.CharField(max_length=100)),
                ("runtime", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SongWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.IntegerField()),
                (
                    "song_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fwpods_be.song"
                    ),
                ),
            ],
        ),
    ]
